import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jiacinto Branducci portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-screen bg-slate-800'>
      <Navbar />
      <main className={inter.className}>{children}</main>
      <Footer />
      </body>
     
    </html>
  )
}
//gradient-to-r from-indigo-500 via-slate-600 to-emerald-900